site_name: VIRAL - Vision-grounded Integration for Reward design And Learning
site_url: https://viral-ucbl1.github.io/
repo_url: https://github.com/VIRAL-UCBL1/VIRAL
repo_name: VIRAL-UCBL1/VIRAL
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
  - scheme: default
    primary: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  language: en
  features:
  - navigation.tabs
  - search.highlight
  - search.suggest
  - search.share
  - content.code.copy
  - content.code.prettify
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.tabs.link
  - navigation.sections
plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          show_signature: true
          show_source: false
nav:
- Home: README.md
- Setup: setup.md
- Documentation:
  - main: code_docs/main.md
  - VIRAL: code_docs/VIRAL.md
  - Environments:
    - Algo: code_docs/Environments/Algo.md
    - CartPole: code_docs/Environments/CartPole.md
    - EnvType: code_docs/Environments/EnvType.md
    - Highway: code_docs/Environments/Highway.md
    - Hopper: code_docs/Environments/Hopper.md
    - LunarLander: code_docs/Environments/LunarLander.md
    - Pacman: code_docs/Environments/Pacman.md
  - LLM:
    - GenCode: code_docs/LLM/GenCode.md
    - LLMOptions: code_docs/LLM/LLMOptions.md
    - OllamaChat: code_docs/LLM/OllamaChat.md
  - log:
    - log_config: code_docs/log/log_config.md
    - LoggerCSV: code_docs/log/LoggerCSV.md
  - PolicyTrainer:
    - CustomRewardWrapper: code_docs/PolicyTrainer/CustomRewardWrapper.md
    - PolicyTrainer: code_docs/PolicyTrainer/PolicyTrainer.md
    - TrainingInfoCallback: code_docs/PolicyTrainer/TrainingInfoCallback.md
  - RLAlgo:
    - DirectSearch: code_docs/RLAlgo/DirectSearch.md
    - Reinforce: code_docs/RLAlgo/Reinforce.md
  - State:
    - State: code_docs/State/State.md
  - utils:
    - utils: code_docs/utils/utils.md
- License: LICENSE.md
