site_name: VIRAL
site_url: https://viral-ucbl1.github.io/
repo_url: https://github.com/VIRAL-UCBL1/VIRAL
repo_name: VIRAL-UCBL1/VIRAL

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  language: en
  features:
    - navigation.tabs
    - search.highlight
    - search.suggest
    - search.share
nav:
  - Home: index.md
  - Setup: setup.md
  - Documentation:
      - Main: code_docs/main.md
      - VIRAL: code_docs/VIRAL.md
      - Utils: 
        - OllamaChat: code_docs/OllamaChat.md
        - State: code_docs/State.md
        - Utils: code_docs/utils.md
        - ObjectivesMetrics: code_docs/ObjectivesMetrics.md
      - RL Algo:
          - DirectSearch: code_docs/RLAlgo/DirectSearch.md
          - PPO: code_docs/RLAlgo/PPO.md
          - Reinforce: code_docs/RLAlgo/Reinforce.md
      
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_signature: true