site_name: VIRAL - Vision-grounded Integration for Reward design And Learning
site_url: https://viral-ucbl1.github.io/
repo_url: https://github.com/VIRAL-UCBL1/VIRAL
repo_name: VIRAL-UCBL1/VIRAL
repo_branch: main
edit_uri: edit/main/docs/
view_uri: blob/main/docs/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette: 
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: en
  features:
    - navigation.tabs
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.prettify
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
nav:
  - Home: README.md
  - Setup: setup.md
  - Documentation:
      - Main: code_docs/main.md
      - VIRAL: code_docs/VIRAL.md
      - Utils: 
        - OllamaChat: code_docs/OllamaChat.md
        - State: code_docs/State.md
        - Utils: code_docs/utils.md
        - ObjectivesMetrics: code_docs/ObjectivesMetrics.md
      - RL Algo:
          - DirectSearch: code_docs/RLAlgo/DirectSearch.md
          - PPO: code_docs/RLAlgo/PPO.md
          - Reinforce: code_docs/RLAlgo/Reinforce.md
  - License: LICENSE
      
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_signature: true
            show_source: false