version: '3.8'

services:
  backend:
    image: back-viral:latest
    ports:
      - "5000:5000"
    volumes:
      - /home/docker/viral/results/videos:/app/videos
      - /home/docker/viral/results/validation:/app/validation
    environment:
      - FLASK_ENV=development

  frontend:
    image: front-viral:latest
    ports:
      - "5173:5173"
