version: '3.8'

services:
  backend:
    image: back-viral:latest
    ports:
      - "5000:5000"
    volumes:
      - /home/docker/viral-XXX/Y:/app/videos
    environment:
      - FLASK_ENV=development

  frontend:
    image: front-viral:latest
    ports:
      - "5173:5173"