name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build MkDocs Site
        run: mkdocs build --config-file ./mkdocs.yml

      - name: Deploy to GitHub Pages Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./site  
          external_repository: VIRAL-UCBL1/VIRAL-UCBL1.github.io
          publish_branch: main
